"""Generate a TS module with the LanguageServerService descriptor closure.

- Reads extracted FileDescriptorProto blobs (.fd.bin)
- Computes the type-reference closure from language_server.proto
- Cleans dangling public/weak dependency indexes, rewrites dependency names
- Topologically orders files
- Emits a TS file: PACKED_FILES = [{name, deps, b64}, ...] in build order

Usage: python gen-descriptors.py <descriptors-dir> <out.ts>
"""
import base64, os, sys
from google.protobuf import descriptor_pb2

def main(src_dir, out_path):
    files = {}
    for f in sorted(os.listdir(src_dir)):
        if not f.endswith('.fd.bin'):
            continue
        fd = descriptor_pb2.FileDescriptorProto()
        fd.ParseFromString(open(os.path.join(src_dir, f), 'rb').read())
        files[fd.name] = fd

    # symbol index: fully-qualified type/enum/service name -> owning file
    sym2file = {}
    def index_msgs(owner, msgs, prefix):
        for m in msgs:
            fq = prefix + '.' + m.name
            sym2file[fq] = owner
            for e in m.enum_type:
                sym2file[fq + '.' + e.name] = owner
            index_msgs(owner, m.nested_type, fq)
    for name, fd in files.items():
        for e in fd.enum_type:
            sym2file[fd.package + '.' + e.name] = name
        index_msgs(name, fd.message_type, fd.package)

    def deps_of(fd):
        out = set()
        def scan(tn):
            if tn and tn.startswith('.'):
                owner = sym2file.get(tn[1:])
                if owner and owner != fd.name:
                    out.add(owner)
        def walk(msgs):
            for m in msgs:
                for f in m.field:
                    scan(f.type_name)
                for e in m.extension:
                    scan(e.type_name); scan(e.extendee)
                walk(m.nested_type)
        walk(fd.message_type)
        for e in fd.extension:
            scan(e.type_name); scan(e.extendee)
        for s in fd.service:
            for m in s.methods if hasattr(s, 'methods') else s.method:
                scan(m.input_type); scan(m.output_type)
        return out

    # closure from the language_server root
    ROOT = 'third_party/jetski/language_server_pb/language_server.proto'
    need, stack = set(), [ROOT]
    while stack:
        n = stack.pop()
        if n in need or n not in files:
            continue
        need.add(n)
        stack.extend(sorted(deps_of(files[n])))

    # topo order (deps first), cycle-safe
    order, state = [], {}
    def visit(n):
        if state.get(n):
            return
        state[n] = 1
        for d in sorted(deps_of(files[n]) & need):
            visit(d)
        order.append(n)
    for n in sorted(need):
        visit(n)

    lines = []
    lines.append('// GENERATED by gen-descriptors.py — do not edit.')
    lines.append('// LanguageServerService descriptor closure, dependency-ordered,')
    lines.append('// public/weak dependency indexes stripped (they crash upb).')
    lines.append('export interface PackedFile { name: string; deps: string[]; b64: string }')
    lines.append('export const PACKED_FILES: PackedFile[] = [')
    for n in order:
        fd = files[n]
        clean = descriptor_pb2.FileDescriptorProto()
        clean.CopyFrom(fd)
        del clean.public_dependency[:]
        del clean.weak_dependency[:]
        del clean.dependency[:]
        deps = sorted(deps_of(fd) & need)
        clean.dependency.extend(deps)
        b64 = base64.b64encode(clean.SerializeToString()).decode()
        lines.append('  {')
        lines.append(f'    name: {n!r},')
        lines.append(f'    deps: {deps!r},'.replace("'", '"'))
        lines.append(f'    b64:')
        # split b64 into 100-char chunks for readable source
        chunks = [b64[i:i+100] for i in range(0, len(b64), 100)]
        lines.append('      ' + ' +\n      '.join(repr(c) for c in chunks) + ',')
        lines.append('  },')
    lines.append(']')
    lines.append('')
    with open(out_path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines).replace("'", '"', ) if False else '\n'.join(lines))
    print(f'closure={len(need)} files, written to {out_path}')

if __name__ == '__main__':
    src = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'agy-recon', 'descriptors-web')
    out = os.path.join(os.path.dirname(__file__), '..', 'src', 'hub', 'descriptors.gen.ts')
    main(src, out)
